services:
  SimpleWeb.Seq:
    image: datalust/seq:latest
    container_name: SimpleWeb.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8080:80"

  SimpleWeb.Seq.WebApi:
    image: seq.webapi
    container_name: SimpleWeb.Seq.WebApi
    build:
      context: .
      dockerfile: Seq/Dockerfile
    ports:
      - "8081:80"

  SimpleWeb.Jeager:
    image: jeager
    build:
      context: .
      dockerfile: Jeager/Dockerfile

  masstransit:
    image: masstransit
    build:
      context: .
      dockerfile: MassTransit/Dockerfile

  masstransitimp:
    image: masstransitimp
    build:
      context: .
      dockerfile: MassTransitImp/Dockerfile
